FROM maven:3.9-eclipse-temurin-21 as builder
WORKDIR /app/common
COPY ./common .
RUN mvn clean install -DskipTests

WORKDIR /app/events
COPY ./events .
RUN mvn clean install -DskipTests

WORKDIR /app/nutrition
COPY ./nutrition-service .
RUN mvn clean install -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /app/nutrition/target/*.jar app.jar
EXPOSE 9020
ENTRYPOINT ["java", "-jar", "app.jar"]
